import { Prisma, TagType } from '@prisma/client';

export const tagsData: Prisma.TagCreateInput[] = [
  { type: TagType.Cuisine, name: 'Italian', slug: 'italian', icon: '🇮🇹' },
  { type: TagType.Cuisine, name: 'Japanese', slug: 'japanese', icon: '🇯🇵' },
  { type: TagType.Cuisine, name: 'Mexican', slug: 'mexican', icon: '🇲🇽' },
  { type: TagType.Cuisine, name: 'Chinese', slug: 'сhinese', icon: '🇨🇳' },
  { type: TagType.Cuisine, name: 'American', slug: 'american', icon: '🇺🇸' },
  { type: TagType.Cuisine, name: 'Indian', slug: 'indian', icon: '🇮🇳' },
  { type: TagType.Cuisine, name: 'Ukrainian', slug: 'ukrainian', icon: '🇺🇦' },
  { type: TagType.Cuisine, name: 'Thai', slug: 'thai', icon: '🇹🇭' },
  { type: TagType.Cuisine, name: 'French', slug: 'french', icon: '🇫🇷' },
  { type: TagType.Cuisine, name: 'Korean', slug: 'korean', icon: '🇰🇷' },
  { type: TagType.Meal_Type, name: 'Breakfast', slug: 'breakfast', icon: '🍳' },
  { type: TagType.Meal_Type, name: 'Lunch', slug: 'lunch', icon: '🥪' },
  { type: TagType.Meal_Type, name: 'Dinner', slug: 'dinner', icon: '🍽️' },
  { type: TagType.Meal_Type, name: 'Snack', slug: 'snack', icon: '🍿' },
  { type: TagType.Meal_Type, name: 'Dessert', slug: 'dessert', icon: '🍰' },
  { type: TagType.Meal_Type, name: 'Appetizer', slug: 'appetizer', icon: '🥟' },
  {
    type: TagType.Meal_Type,
    name: 'Drink / Smoothie',
    slug: 'drink-smoothie',
    icon: '🥤',
  },
  {
    type: TagType.Meal_Type,
    name: 'Soup / Broth',
    slug: 'soup-broth',
    icon: '🍲',
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'Vegetarian',
    slug: 'vegetarian',
    icon: '🥗',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'Vegan',
    slug: 'vegan',
    icon: '🌱',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'Gluten-Free',
    slug: 'gluten-free',
    icon: '🌾',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'No Tree Nuts',
    slug: 'no-tree-nuts',
    icon: '🌰',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'Lactose-Free',
    slug: 'lactose-free',
    icon: '🥛',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'No Pork',
    slug: 'no-pork',
    icon: '🐷',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'No Beef',
    slug: 'no-beef',
    icon: '🐮',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'No Shellfish',
    slug: 'no-shellfish',
    icon: '🦐',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'No Sweets',
    slug: 'no-sweets',
    icon: '🍰',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'No Peanuts',
    slug: 'no-peanuts',
    icon: '🥜',
    isSelectable: true,
  },
  {
    type: TagType.Dietary_Restrictions,
    name: 'Halal',
    slug: 'halal',
    icon: '☪️',
    isSelectable: true,
  },
  { type: TagType.Spice_Level, name: 'Mild', slug: 'mild', icon: '🧂' },
  { type: TagType.Spice_Level, name: 'Medium', slug: 'medium', icon: '️🌶️' },
  { type: TagType.Spice_Level, name: 'Spicy', slug: 'spicy', icon: '🌶️🌶️' },
  {
    type: TagType.Spice_Level,
    name: 'Extra Spicy',
    slug: 'extra-spicy',
    icon: '🌶️🌶️🌶️',
  },
];
